include: package:very_good_analysis/analysis_options.yaml

analyzer:
  language:
    strict-inference: false
    strict-casts: false
  exclude:
    - pubspec.yaml

linter:
  rules:
    public_member_api_docs: false
    type_annotate_public_apis: false
    discarded_futures: false
