name: belaraby
description: "An app for learning Arabic."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: "3.9.0"
  flutter: "3.35.2"

dependencies:
  carousel_slider: ^5.1.1
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_tts: ^4.2.3
  go_router: ^16.2.4
  google_sign_in: ^7.2.0
  intl: ^0.20.2
  intl_utils: ^2.8.12
  supabase_flutter: ^2.10.3

dev_dependencies:
  analyzer: ^8.2.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: 10.0.0

flutter_intl:
  enabled: true
  main_locale: ar
  class_name: L10n
  arb_dir: lib/l10n
  output_dir: lib/l10n

flutter:
  uses-material-design: true
