# Project Information
site_name: Belaraby Docs
site_description: Centralized docs for the Belaraby project
repo_name: https://github.com/FlowbitLabs/belaraby

# Theme Configuration
theme:
  name: material
  language: en
  font:
    text: Poppins
    code: JetBrains Mono
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  # Built-in Material features
  features:
    features:
      - navigation.expand # Expand the current section automatically
      - navigation.sections # Show second-level sections in sidebar
      - navigation.instant # Instant loading between pages
      - navigation.tracking # Highlight current section
      - navigation.tabs # Top-level sections as tabs
      - toc.integrate # Merge page TOC into sidebar
      - navigation.path
      - navigation.indexes
      - search.suggest
      - search.highlight
      - search.share
      - announce.dismiss
      - content.action.edit
      - content.action.view
      - content.code.copy
      - content.code.annotate
      - content.tooltips
      - content.tabs.link
      - toc.follow

# Location of documentation source files
docs_dir: docs/

# Custom Styling
extra_css:
  - assets/stylesheets/extra.css

# Plugins
plugins:
  - search
  - awesome-nav

# Markdown Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - tables
  - pymdownx.blocks.caption
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets:
      base_path: _doc_scripts/internal_files
      auto_append:
        - abbreviations.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid # Enables Mermaid diagrams
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
